---
title: "MIB for Law Enforcement - Setting up Combined Sample"
author: "Dr. Calvin Lai"
date: "07/23/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
always_allow_html: yes
---

# TO DO: 
# Create a combined S1T1 + S2T1 without T1T2 for differential attrition analyses
<!-- # t1_no_t1t2 <- anti_join(t1, t1t2, by = "id") %>% select(knowledge.t1, theories.t1, biasworry.t1, respect, centrality, strategy_use,
                         # frequency_black, frequency_asian, frequency_hispanic, frequency_gay, frequency_trans, yearsworked, race_white, race_black, gender_d, rank, yearsworked) -->

```{r setup, include = FALSE}
# Package names
packages <- c("sjPlot",  "psych", "foreign", "tidyverse", "glue", "effsize", "cowplot", "lme4", "lmerTest", "corrplot", "summarytools")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
rm(list = c("packages", "installed_packages"))

#Data to load 
s1t1t2 <- read_csv("C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_all-time1-2.csv", guess_max = min(12000))
s2t1t2 <- read_csv("C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mibstudy2_t1t2-clean.csv", guess_max = min(12000))

# Diagnosing similarities + differences in two datasets. Exported the data and inspected using diffchecker.com
# write_csv(s1t1t2[,order(colnames(s1t1t2))], "C:/Users/Calvin/Downloads/temp1.csv")
# write_csv(s2t1t2[,order(colnames(s2t1t2))], "C:/Users/Calvin/Downloads/temp2.csv")

# Removing non-shared variables
s1t1t2 <- s1t1t2 %>% dplyr::select(-c(initials.t1, initials.t2, notes.t1, notes.t2,
                                      session_date, session_id.t1, session_id.t2))
s2t1t2 <- s2t1t2 %>% dplyr::select(-c(
  biasworry_21, DistributionChannel.x, DistributionChannel.y, duration.x, duration.y, EndDate.x, EndDate.y, 
  facilitator1, facilitator2, Finished.x, Finished.y, id3_middle_street.x, id3_middle_street.y, 
  id3_mom_middle.x, id3_mom_middle.y, id3_mom_month.x, id3_mom_month.y, id3_mom_street.x, id3_mom_street.y, 
  id3_month_middle.x, id3_month_middle.y, id3_month_street.x, id3_month_street.y, id3_siblings_middle.x, 
  id3_siblings_middle.y, id3_siblings_mom.x, id3_siblings_mom.y, id3_siblings_month.x, id3_siblings_month.y, 
  id3_siblings_street.x, id3_siblings_street.y, knowledge_21, Progress.x, Progress.y, 
  RecordedDate.x, RecordedDate.y, ResponseId.x, ResponseId.y, StartDate.x, StartDate.y, 
  Status.x, Status.y, strategy_21, theories_21, UserLanguage.x, UserLanguage.y))
s2t1t2 <- s2t1t2 %>% dplyr::select(-c(t1t2delay, training_date))

# Creating special versions for variables that differed in variable type between the two datasets.
s1t1t2 <- s1t1t2 %>% dplyr::rename(
  id_siblings.t1.s1 = id_siblings.t1, id_mom.t1.s1 = id_mom.t1, id_month.t1.s1 = id_month.t1, id_middle.t1.s1 = id_middle.t1, 
  id_siblings.t2.s1 = id_siblings.t2, id_mom.t2.s1 = id_mom.t2, id_month.t2.s1 = id_month.t2, id_middle.t2.s1 = id_middle.t2,   
  race.s1 = race, gender.s1 = gender, education.s1 = education)
s1t1t2 <- s1t1t2 %>% mutate(sample = 1)
s2t1t2 <- s2t1t2 %>% dplyr::rename(
  id_siblings.t1.s2 = id_siblings.t1, id_mom.t1.s2 = id_mom.t1, id_month.t1.s2 = id_month.t1, id_middle.t1.s2 = id_middle.t1, 
  id_siblings.t2.s2 = id_siblings.t2, id_mom.t2.s2 = id_mom.t2, id_month.t2.s2 = id_month.t2, id_middle.t2.s2 = id_middle.t2,   
  race.s2 = race, gender.s2 = gender, education.s2 = education)
s2t1t2 <- s2t1t2 %>% mutate(sample = 2)

# Creating full dataset
t1t2 <- full_join(s1t1t2,s2t1t2)
freq(t1t2$race.s1)
freq(t1t2$race.s2)

# Creating race var
t1t2 <- t1t2 %>% mutate(
  race = case_when(
    is.na(race.s1) == F  ~ race.s1,
    race.s2 == 1 ~ "white",
    race.s2 == 2 ~ "black",
    race.s2 == 3 ~ "hispanic",
    race.s2 == 4 ~ "asian",
    race.s2 == 5 ~ "multi"    
  )
)
  
# Creating long data for long analyses: T1 + T2
timePivot <- function(data){
  data %>%  pivot_longer(
             cols = ends_with(c("t1", "t2", "t3")), 
             names_to=(c(".value", "time")), names_sep = ".t(?=\\d)") %>%
             select(id, time, everything())
}

t1t2Long <- t1t2 %>% select(id, 
                          knowledge.t1, theories.t1, strategy_use, biasworry.t1, 
                          knowledge.t2, theories.t2, biasworry.t2, 
                          strategy_intend, strat_know.t2, strat_efficacy.t2, strat_mot.t2,                           
                          substitution_use, substitution_intend,
                          perspective_use, perspective_intend,
                          mindful_use, mindful_intend, 
                          frequency_black, frequency_hispanic, frequency_asian,
                          frequency_gay, frequency_trans,
                          respect, centrality, yearsworked, rank,  
                          race_white, race_black, gender_d, education_ba,
                          attendance, facilduo_gender, facilduo_race, 
                          facilduo_le, facilduo_relatedle, facilduo_relatedle_nole, sample) %>% 
                          dplyr::rename(strategy.t1 = strategy_use, 
                                 strategy.t2 = strategy_intend,
                                 substitution.t1 = substitution_use, substitution.t2 = substitution_intend,
                                 perspective.t1 = perspective_use, perspective.t2 = perspective_intend,
                                 mindful.t1 = mindful_use, mindful.t2 = mindful_intend)

t1t2LongKnowledgeT1 <- t1t2Long %>% dplyr::rename(knowledge = knowledge.t1) %>% 
  select(c(-knowledge.t2)) %>% timePivot()
                        
t1t2LongTheoriesT1 <- t1t2Long %>% dplyr::rename(theories = theories.t1) %>% 
  select(c(-theories.t2)) %>% timePivot()

t1t2LongBiasworryT1 <- t1t2Long %>% dplyr::rename(biasworry = biasworry.t1) %>% 
  select(c(-biasworry.t2)) %>% timePivot()    

t1t2LongStratKnowT1 <- t1t2Long %>% dplyr::rename(strat_know = strat_know.t2)  %>% timePivot()          
t1t2LongStratEfficacyT1 <- t1t2Long %>% dplyr::rename(strat_efficacy = strat_efficacy.t2)  %>% timePivot()          
t1t2LongStratMotT1 <- t1t2Long %>% dplyr::rename(strat_mot = strat_mot.t2)  %>% timePivot()      

t1t2Long <- t1t2Long %>% timePivot()
 
# Merging session info files
s1sessioninfo <- read_csv("C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_sessioninfo-clean.csv", guess_max = min(12000))
s2sessioninfo <- read_csv("C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mibstudy2_sessioninfo-clean.csv", guess_max = min(12000))
combined_sessioninfo <- full_join(s1sessioninfo,s2sessioninfo)

# Saving files
write_csv(t1t2, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2.csv")
write_csv(t1t2Long, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long.csv")
write_csv(t1t2LongBiasworryT1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long_biasworryt1.csv")
write_csv(t1t2LongKnowledgeT1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long_knowledget1.csv")
write_csv(t1t2LongTheoriesT1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long_theoriest1.csv")
write_csv(t1t2LongStratKnowT1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long_stratknowt1.csv")
write_csv(t1t2LongStratEfficacyT1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long_stratefficacyt1.csv")
write_csv(t1t2LongStratMotT1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1t2_long_stratmott1.csv")
write_csv(combined_sessioninfo, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_sessioninfo.csv")

```

```{r differential attrition}
##### Differential Attrition Setup ----
# Creating cohen d round function
cohensd <- function(group1, group2){
  round(effsize::cohen.d(group2, group1, na.rm = T)$estimate, 2)
}

# Creating combined  T1 for assessing differential attrition
s1t1 <- read_csv("C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_t1-clean.csv", guess_max = min(12000))
s2t1 <- read_csv("C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mibstudy2_t1-clean.csv", guess_max = min(12000))

# Removing non-shared variables
s1t1 <- s1t1 %>% dplyr::select(-c(initials.t1, notes.t1, 
                                      session_id.t1))
s2t1 <- s2t1 %>% dplyr::select(-c(
  DistributionChannel, duration, EndDate, 
  Finished, id3_middle_street, 
  id3_mom_middle, id3_mom_month, id3_mom_street, 
  id3_month_middle, id3_month_street, id3_siblings_middle, 
  id3_siblings_mom,  id3_siblings_month, 
  id3_siblings_street, Progress,
  RecordedDate, ResponseId, StartDate, 
  Status, UserLanguage))

# Creating special versions for variables that differed in variable type between the two datasets.
s1t1 <- s1t1 %>% dplyr::rename(
  id_siblings.t1.s1 = id_siblings.t1, id_mom.t1.s1 = id_mom.t1, id_month.t1.s1 = id_month.t1, id_middle.t1.s1 = id_middle.t1, 
  race.s1 = race, gender.s1 = gender, education.s1 = education)
s1t1 <- s1t1 %>% mutate(sample = 1)
s2t1 <- s2t1 %>% dplyr::rename(
  id_siblings.t1.s2 = id_siblings.t1, id_mom.t1.s2 = id_mom.t1, id_month.t1.s2 = id_month.t1, id_middle.t1.s2 = id_middle.t1, 
  race.s2 = race, gender.s2 = gender, education.s2 = education)
s2t1 <- s2t1 %>% mutate(sample = 2)

# Combining the T1 samples
t1 <- full_join(s1t1,s2t1)
write_csv(t1, "C:/Users/Calvin/Documents/Dropbox/Projects/mib/data/mib_combined_t1.csv")

# Creating datasets for assessing differential attrition
# extra yearsworked at the end, but it doesn't matter. Didn't fix since it didn't cause problems
t1_no_t1t2 <- anti_join(t1, t1t2, by = "id") %>% select(knowledge.t1, theories.t1, biasworry.t1, respect, centrality, strategy_use,
                         frequency_black, frequency_asian, frequency_hispanic, frequency_gay, frequency_trans, yearsworked, race_white, race_black, gender_d, rank, yearsworked, education_ba)

temp_t1t2 <- t1t2 %>% select(knowledge.t1, theories.t1, biasworry.t1, respect, centrality, strategy_use,
                         frequency_black, frequency_asian, frequency_hispanic, frequency_gay, frequency_trans, yearsworked, race_white, race_black, gender_d, rank, yearsworked, education_ba)

# Creating function for checking differential attrition
attritionCheck <- function(group1, group2) {
  output <- data.frame(nrow(length(group1)), ncol(10))
  for(i in 1:length(group1)) {
    output[i, 1] <- names(group1[i]) # Variable name
    output[i, 2] <- cohensd(group1[[i]], group2[[i]]) # Cohen's d
    output[i, 3] <- t.test(group1[i], group2[i])[3] # p-value
    output[i, 3] <- round(as.numeric(output[i, 3]), 4)
    output[i, 4] <- p.adjust(t.test(group1[i], group2[i])[3], method="BH", n = length(group1)) # adjusted p-value
    output[i, 4] <- round(as.numeric(output[i, 4]), 4)    
    output[i, 5] <- round(mean(group1[[i]], na.rm = T), 2) # m1
    output[i, 6] <- round(mean(group2[[i]], na.rm = T), 2) # m2
    output[i, 7] <- round(sd(group1[[i]], na.rm = T), 2) # sd1
    output[i, 8] <- round(sd(group2[[i]], na.rm = T), 2) # sd2
    output[i, 9] <- if_else(as.numeric(output[i, 3]) < .05, "*", "")
    output[i, 10] <- if_else(as.numeric(output[i, 4]) < .05, "*", "")
    
  }
colnames(output) <- c("variable", "cohens d", "p-value", "p-adj", "m1", "m2", "sd1", "sd2", "sig", "sig-adj")
output  
}

attritionCheck(t1_no_t1t2, temp_t1t2)
```


